config/routes.rb
DemoApp::Application.routes.draw do
 resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :entries,    only: [:create, :destroy]
  resources :comments,   only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#Contact', via: 'get'

end

app/views/shared/_comment_form.html.erb
<%= form_for(Comment.new) do |f| %>
  <div class="field">
    <span>
    	<%= f.text_field :content, placeholder: "cmt..." %>
    	<%= f.hidden_field :entry_id, value: entry.id %> 
    	<%= f.hidden_field :user_id_cmt, value: current_user.id %>
	</span>
  </div>
  <%= f.submit "Comment", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_entry_form.html.erb
<%= form_for(@entry) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text_field :title, placeholder: "Compose new title entry..." %>
    <%= f.text_area :body, placeholder: "Compose new body entry..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>

    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="entries">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="title"><%= feed_item.title %></span>
  <span class="body"><%= feed_item.body %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>

  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.title %>
  <% end %>

  <% entry = feed_item %>
  <% if entry.comments.any? %>
	  <h4>Comments (<%= entry.comments.count %>)</h4>
    <% @cmts = entry.comments.paginate(:page => params[:comment_page], :per_page => 5)%>
	  <li class="entries">
	          <% @cmts.each do |i|%>
	            <li>
	              <span class="content">
	              	<b><%= User.find(i.user_id_cmt).name %></b>
	                <i><%= i.content %></i>
	              </span>
                <span class="timestamp">
                  <i>Commented <%= time_ago_in_words(i.created_at) %> ago.</i>
                </span>
	            </li>
	          <%end %>
            <%= will_paginate @cmts, :param_name => 'comment_page'%>
	  </li>
  <% end %>
  <% if signed_in? %>
	  <%= render 'shared/comment_form',entry: entry%>
  <%end%>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.entries.count, "entry") %>
</span>